version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5438:5438"
    volumes:
      - my-db:/var/lib/postgresql/data

volumes:
  my-db:
